# Tomcat 线程配置
server:
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 2000
    threads:
      max: 400
      min-spare: 10
    accept-count: 500

# ======== 任务线程池配置 ========
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ======== 数据源配置 ========
spring:
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://mysql:3306/boot3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
  # ======== Redis配置 ========
  redis:
    redisson:
      file: classpath:redisson/redisson-prod.yaml

# ======== Security 配置 ========
security:
  # SM4 加密密钥
  sk: 1234567890123456

# ======== JWT密钥配置 ========
jwt:
  secret: 1234567890123456
  expirationTime: 604800
  issuer: boot
  header: Authorization
  tokenHead: Bearer