version: "3.9"
services:
  spring-app:
    image: "spring-boot-app:latest"
    container_name: spring-boot3
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - app-env-network