version: "3.9"
services:
  mysql:
    image: 'mysql:8.0.32'
    container_name: mysql-server
    restart: always
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "13306:3306"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
    networks:
      - app-env-network

  redis:
    image: 'redis:7.2.3-alpine'
    container_name: redis
    command: 'redis-server /etc/redis/redis.conf'
    volumes:
      - 'redis_data:/data/redis'
      - './redis/redis.conf:/etc/redis/redis.conf'
    ports:
      - '16379:6379'
    restart: always
    tty: true
    stdin_open: true
    networks:
      - app-env-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-env-network:
    driver: bridge