global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 注意IP换为你的应用IP:Port
      - targets: [ '127.0.0.1:8080' ]
